### ISSUE TITLE
Build newest releases with CVE fixes

### ISSUE THREAD

**Issue by Kidswiss** [saltstack/saltdocker#22]
Hi

As far as I can see the latest docker images don't contain the fixes for CVE-2020-11651 and CVE-2020-11652.

For example the latest 3000.X image on docker hub is 3000.1 which is still vulnerable.

Also the tags don't seem to follow docker best practises. Usually the tag only containing the major version points to the newest minor and bugfix version of the images. E.g. `someimage:2` contains `someimage:2.1.3`. I was under the assumption that's also the case here and felt save until I found some cryptominers on my hosts (https://github.com/saltstack/salt/issues/57057).

**Comment by s0undt3ch** [comment]
I believe this issue can now be closed since the available versions have been updated for a while now.
As for the versioning convention, that's exactly what we do, however, we're still in the process of making these docker images support more official and automate the containers build process upon each release, right now, we still have to manually kick off a build upon each release.

Please let us know if this is still an issue.
